FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

# Install necessary packages
RUN apt-get update && apt-get install -y \
    git \
    wget \
    bzip2 \
    ffmpeg \
    python3 \
    python3-pip \
    ca-certificates

COPY ./requirements.txt /requirements.txt

RUN pip install -r requirements.txt

EXPOSE 8888
