FROM nvidia/cuda:11.8.0-devel-ubuntu20.04

COPY ./environment.yaml /environment.yaml

# Install necessary packages
RUN apt-get update && apt-get install -y \
    wget \
    bzip2 \
    git \
    ca-certificates

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh && \
    bash /tmp/miniconda.sh -b -p /opt/conda && \
    rm /tmp/miniconda.sh && \
    ln -s /opt/conda/bin/conda /usr/local/bin/conda

ENV PATH=/opt/conda/bin:$PATH

RUN conda env create --file environment.yaml

EXPOSE 8888
